# Generated by Django 4.1.6 on 2023-05-13 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(max_length=50)),
                ('User', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.TextField()),
                ('street', models.TextField()),
                ('num_home', models.CharField(max_length=10)),
                ('col_apartment', models.FloatField()),
                ('Company', models.ManyToManyField(to='main.company')),
            ],
        ),
        migrations.CreateModel(
            name='Bypass_result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment', models.FloatField()),
                ('open_close', models.FloatField()),
                ('reaction', models.FloatField()),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.company')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.home')),
            ],
        ),
    ]
