# Generated by Django 4.1.6 on 2023-05-13 22:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_people'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='User',
        ),
        migrations.DeleteModel(
            name='People',
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
